@plr = player()


@hero = associative_array(
            'name': '§3M§fi§3st§0e§3rF§0a§3nt§fa§3st§0i§3c
            'class': 'misterfantastic',
            'sig': 'p1JBPOnSyJDxkLCqDqfFzRwHt0NDDyyWonfs62fL/ySNjlXtalw8m2w+KYtKkimgjbYU+QQlRP5f5s6E7EtcLQ8Kv4AX/fQ40XwDgDzarzCw/aAOO7SbOB6wgQN3Ey4AWyoN6M8dtkQPy7x7TbMg7hzlPWXs8t/lM88agWTXDP3EXO+RIgdkP11ZO9qZx6FllmGzqAPlvrxXsJSVjnN+srIQxbMsnOtmwPtN3wycTdl9un0j6EMPebyForT3Z6OB3xzwqw7ap6q4OpC/gVZ9I35iOsp0De+bsYWIjnpoYPuAmO3ZXlhdLACYJxgBa+q5EUTVk/VmdIQiqSA9/16DygWXGIevnxfi8j6ypyQvAk+mspTg4ZHHLKIdsLBR/KeLFdpwP9TVflBN5SdFJEnH1OXTB6DnA/SD4kBDCQirAGZ6W2MEpfPnaC0Zh0If1NK8fQRjRmw2CQYCSRGBKeZp4yJlSs/lt8xmfKMqkY10nEvy2pYexDof7nc2WoJHhYpQ+hkoEZLqheU85vsCCMhsLzINz/sBMEhhP/UOECigSfSSsRmAePwBGa8JmytoKHCoK8/Yjb8eo8oUKYxdCFjFDPI+u/awmp0x46dYf3kWzJr84/RiUCUFt35c1UFIGWUfbKJw1ZlqFFBXlxAo0ny36Tj5i139nomnfwnAo5Tj8GA=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTYwMDUwNzMyMzQsInByb2ZpbGVJZCI6IjRmZjg2N2Y1NmNhYjQxM2U5ZmFkZTRkNzdjYTQ4Nzc4IiwicHJvZmlsZU5hbWUiOiJUYWl5b3VfIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9iZmFmZGRhM2JjYTQ0MDc1NDdiOWQ1YWM0YTlhMzMyMWQwYWZhZWVjZjlhMWU3ZmFhY2U5YTRjY2VlNjcifX19',
            'trail': '',
            'op': 'false',
            'speech': "My father shall no longer harm us.",
            'powers': array(
                "/buff",
                "/disguise",
                "/undisguise"
               
            ),
            'buffs': array(
               
               
